config/routes.rb
Rails.application.routes.draw do
  resources :multi_tasks 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/multi_task.rb
class MultiTask
  include Mongoid::Document
  validates_presence_of :end_date, allow_nil: true
  validates_presence_of :start_date
  validates_presence_of :description

  field :title, type: String, default: ""
  field :start_date, type: Time
  field :end_date, type: Time
  field :description, type: String
  field :finished, type: Mongoid::Boolean
  field :priority, type: Integer, default: 1
  field :frequency, type: Integer, default: 999
  field :parent, type: String, default: ""

  def subtasks
    MultiTask.where(parent: id)
  end

  def parent_task
    return nil if parent.nil?
    MultiTask.find(parent)
  end

  def formatted_start_date
    start_date.to_date.strftime("%d/%m/%Y")
  end

  def formatted_end_date
    end_date.to_date.strftime("%d/%m/%Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/multi_tasks_controller.rb
class MultiTasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :possible_parents, only: [:new, :edit]

  def new
    @task = MultiTask.new
  end

  def index
    @multitasks = MultiTask.where(parent: "")
    @subtasks   = MultiTask.where(:parent.ne => '')

    # @multitasks = @tasks.map do |task|
    #   { task: task, subtasks: @subtasks.select { |sub| sub.parent == task.id.to_s || nil  } }
    # end
    respond_to do |format|
      format.html
    end
  end

  def sub_tasks
    @multitask = MultiTask.find(params[:multi_task_id])

    respond_to do |format|
      format.js
    end
  end

  def create
    @task = MultiTask.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Tarefa criada com sucesso.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to multi_task_path(@task) , notice: 'Tarefa atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to multi_tasks_url, notice: 'A tarefa foi removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  def possible_parents
    @parents = MultiTask.where(parent: "").map { |p| [p.description, p.id.to_s] } || []
  end

  def set_task
    @task = MultiTask.find(params[:id])
  end

  def task_params
    format_params_dates
    params.require(:multi_task).permit(:title, :start_date,
      :end_date, :description, :finished, :priority, :frequency, :parent)
  end

  def format_params_dates
    params[:multi_task]["start_date"] = format_start_date

    params[:multi_task]["end_date"] = format_end_date

    remove_useless_dates
  end

  def remove_useless_dates
    params[:multi_task].delete_if do |k,v|
      k =~ /[start,end]_date\([1-9]+i\)/
    end
  end

  def format_end_date
    Date.parse("#{params[:multi_task]["end_date(3i)"].to_s}/#{params[:multi_task]["end_date(2i)"].to_s}/#{params[:multi_task]["end_date(1i)"].to_s}") if params[:multi_task]["end_date(3i)"]
  end

  def format_start_date
    Date.parse("#{params[:multi_task]["start_date(3i)"].to_s}/#{params[:multi_task]["start_date(2i)"].to_s}/#{params[:multi_task]["start_date(1i)"].to_s}") if params[:multi_task]["start_date(3i)"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/multi_tasks_helper.rb
module MultiTasksHelper

  def options(task)
    options = [ link_to('Detalhes', task, class: "dropdown-item"),
     link_to('Editar', edit_multi_task_path(task), class: "dropdown-item"),
     link_to('Excluir', task, method: :delete, data: { confirm: 'Excluir: Tem certeza?' }, class: "dropdown-item") ]

    content_tag :div, class: "dropdown " do
      button =  button_tag 'Opções', class: 'btn btn-secondary dropdown-toggle', data: { toggle: :dropdown }
      content = content_tag :div, class: "dropdown-menu" do
        options.join.html_safe
      end
      (button + content).html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <head>
    <title>MyTodoList</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", :async => !Rails.env.development?, "turbolinks-data-track" => true %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/multi_tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> Não é possível salvar essa tarefa:</h2>
       <ul>
         <% @task.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
       </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="row">
    <div class="col-3">
      <%= f.label :start_date %><br>
      <%= f.date_select :start_date, order: [:day, :month, :year] %>
    </div>

    <div class="col-3">
      <%= f.label :end_date %><br>
      <%= f.date_select :end_date, order: [:day, :month, :year]%>
    </div>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority, min: 1, max: 10 %>
  </div>

  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.select :frequency, { '1 dia': 1, 'diariamente': 99  } %>
  </div>
  <br>

  <div class="field">
    <%= f.label :parent %><br>
    <%= f.select :parent, options_for_select(@parents), {include_blank: true, multiple: true, size: 10} %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
$("#button_new_task").click( function() {
  var $div = $('div[id^="multi_task"]:last');
  var num = parseInt( $div.prop("id").match(/\d+/g), 10 ) +1;
  if(num < 3)
    {
      $div.after($("div[id^='multi_task']:first").clone().prop('id', 'address'+num ).wrap('<div/>').parent().html());
    }
  })
</script>

app/views/multi_tasks/_multi_tasks.html.erb
  <div class="modal" id="sub-task-modal">
    <div class="modal-dialog modal-lg" >
      <div class="modal-content" >
        <div class="card">
          <div class="card-body">
            <h1 class="card-title">Tarefas</h1>
            <div class="col-2">
              <%= link_to 'Nova tarefa', new_multi_task_path, class: "btn btn-primary active" %>
            </div>
            </br>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Finalizado?</th>
                  <th>Descrição</th>
                  <th>Data de inicio</th>
                  <th>Data de fim</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <tbody>
                <% @multitasks.each do |task| %>
                    <tr id=<%= "sub_task"+task.id.to_s %> class=<%= "sub_task"+task.id.to_s %> >
                      <td><%= form_for(task) do |f| %>
                        <%= f.check_box :finished %>
                      <% end %></td>
                      <td><%= task.description %></td>
                      <td><%= task.formatted_start_date %></td>
                      <td><%= task.formatted_end_date %></td>
                      <td><%= options(task) %></td>
                    </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/multi_tasks/edit.html.erb
<h1> Tarefa '<%= @task.title %>'</h1> 
<%= render 'form' %>
<%= link_to 'Voltar', multi_tasks_path %>

app/views/multi_tasks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <div id="testing"></div>

  <div class="card">
    <div class="card-body">
      <h1 class="card-title" >Tarefas</h1>
      <div class="col-2">
        <%= link_to 'Nova tarefa', new_multi_task_path, class: "btn btn-primary active" %>
      </div>
      </br>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Finalizado?</th>
            <th>Descrição</th>
            <th>Data de inicio</th>
            <th>Data de fim</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @multitasks.each do |multitask| %>
            <tr>
              <td><%= form_for(multitask) do |f| %>
                <%= f.check_box :finished %>
              <% end %></td>
              <td><%= multitask.description %></td>
              <td><%= multitask.formatted_start_date %></td>
              <td><%= multitask.formatted_end_date %></td>
              <td><%= options(multitask) %></td>
              <td><%= button_tag "sub-tarefas", id: "sub-tarefa", type: "button", class: "btn btn-primary", data: { toggle: "modal", target: "#sub-task-modal" } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render partial: "multi_tasks" %>

app/views/multi_tasks/new.html.erb
<h1>Nova tarefa</h1>
<%= render 'form' %>
<%= link_to 'Voltar', multi_tasks_path %>

app/views/multi_tasks/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table">
  <thead>
    <tr>
      <th>Título</th>
      <th>Descrição</th>
      <th>Data de inicio</th>
      <th>Data de fim</th>
      <th>Prioridade</th>
      <th>Frequencia</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.title %></td>
      <td><%= @task.description %></td>
      <td><%= @task.formatted_start_date %></td>
      <td><%= @task.formatted_end_date %></td>
      <td><%= @task.priority %></td>
      <td><%= @task.frequency %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Editar', edit_multi_task_path(@task) %> |
<%= link_to 'Voltar', multi_tasks_path %>

app/views/multi_tasks/sub_tasks.js.erb
//$("#modal-body").append('<%= escape_javascript render partial: "multi_task", locals: "#{@multitasks}" %>')